language: go
install: go get -v github.com/spf13/hugo
script:
  - python --version
  - sudo pip install awscli
  - hugo && aws s3 sync public/ s3://colelawrence.com/ --delete
notifications:
    email:
        on_failure: always
branches:
  only:
  - master
